// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1923.NewArial_Assist;

import org.usfirst.frc1923.NewArial_Assist.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;
import org.firstrobotics1923.util.XboxController;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // Another type of button you can create is a DigitalIOButton, which is
    // a button or switch hooked up to the cypress module. These are useful if
    // you want to build a customized operator interface.
    // Button button = new DigitalIOButton(1);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick leftStick;
    public Joystick rightStick;
    public JoystickButton start;
    public JoystickButton a;
    public JoystickButton b;
    public JoystickButton x;
    public JoystickButton y;
    public JoystickButton lB;
    public JoystickButton rB;
    public JoystickButton back;
    public JoystickButton leftClick;
    public JoystickButton rightClick;
    public Joystick xboxController;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightStick = new Joystick(2);
        leftStick = new Joystick(1);
        xboxController = new XboxController(3);
        
        //Components.robotDrive.drive(Components.leftStick.getCoalescedY(), Components.rightStick.getCoalescedY());
        // Create XBOX buttons
        rightClick = new JoystickButton(xboxController, 10);
        
        leftClick = new JoystickButton(xboxController, 9);
        
        back = new JoystickButton(xboxController, 7);
        
        rB = new JoystickButton(xboxController, 6);
        
        lB = new JoystickButton(xboxController, 5);
        
        
        x = new JoystickButton(xboxController, 3);
        
        b = new JoystickButton(xboxController, 2);
        
        a = new JoystickButton(xboxController, 1);
        
        start = new JoystickButton(xboxController, 8);
        
        // Assign commands to buttons
        rightClick.whenPressed(new ShooterRaiseAngleCommand());
        leftClick.whenPressed(new ShooterLowerAngleCommand());
        back.whenPressed(new ShooterStopCommand());
        rB.whenPressed(new IntakeMotorReverseCommand());
        lB.whenPressed(new IntakeMotorForwardCommand());
        x.whenPressed(new IntakeAngleOutCommand());
        b.whenPressed(new IntakeAngleInCommand());
        a.whenPressed(new XboxButtonACommand());
        start.whenPressed(new ShooterStartCommand());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("IntakeAngleInCommand", new IntakeAngleInCommand());

        SmartDashboard.putData("IntakeAngleOutCommand", new IntakeAngleOutCommand());

        SmartDashboard.putData("IntakeMotorForwardCommand", new IntakeMotorForwardCommand());

        SmartDashboard.putData("IntakeMotorOffCommand", new IntakeMotorOffCommand());

        SmartDashboard.putData("IntakeMotorReverseCommand", new IntakeMotorReverseCommand());

        SmartDashboard.putData("ShooterLowerAngleCommand", new ShooterLowerAngleCommand());

        SmartDashboard.putData("ShooterRaiseAngleCommand", new ShooterRaiseAngleCommand());

        SmartDashboard.putData("ShooterStartCommand", new ShooterStartCommand());

        SmartDashboard.putData("ShooterStopCommand", new ShooterStopCommand());

        SmartDashboard.putData("DriveDistanceCommand", new DriveDistanceUsingEncoderCommand());

        SmartDashboard.putData("DriveCommand", new DriveWithJoyStickCommand());

        //SmartDashboard.putData("AutoAimPanCommand", new AutoAimPanCommand());
        
        SmartDashboard.putData("Command Group 1", new CommandGroup1());

        SmartDashboard.putData("XboxButtonACommand", new XboxButtonACommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getleftStick() {
        return leftStick;
    }

    public Joystick getrightStick() {
        return rightStick;
    }

    public Joystick getXboxController() {
        return xboxController;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

